spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otzbIv
    username: postgres
    password: 5333168tema
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # или none (если не хочешь, чтобы схема трогалась)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080